#whiteList:
#  - Bug
#  - Chore

updateDocsComment: >
  Thanks for opening this pull request! The maintainers of this repository would appreciate it if you would update some of our documentation based on your changes.
repository:
  name: testing-things
  description: this repo is radical dude ugh
  has_projects: false
