newPRWelcomeComment: >
  Thanks so much for opening your first PR here, make sure to follow the contributing guidelines!

firstPRMergeComment: >
  Congrats on merging your first pull request here!

firstIssueWelcomeComment: >
  Thanks for opening this issue, please make sure you follow our issue template!
